# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/stock_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/stock_info.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x16proto/stock_info.proto\"\x94\x04\n\tStockInfo\x12\x10\n\x08stock_id\x18\x01 \x01(\t\x12\x31\n\x0csummary_info\x18\x02 \x01(\x0b\x32\x1b.StockInfo.StockSummaryInfo\x12-\n\ndaily_info\x18\x03 \x03(\x0b\x32\x19.StockInfo.StockDailyInfo\x1a\x98\x01\n\x10StockSummaryInfo\x12\x18\n\x0cmarket_place\x18\x01 \x01(\t:\x02us\x12\x10\n\x08ipo_date\x18\x02 \x01(\t\x12\x1e\n\x10has_option_trade\x18\x03 \x01(\x08:\x04true\x12\x16\n\x0emarket_value_b\x18\x04 \x01(\x01\x12\x0e\n\x06is_etf\x18\x05 \x01(\x08\x12\x10\n\x08is_china\x18\x06 \x01(\x08\x1a\xf7\x01\n\x0eStockDailyInfo\x12\x0c\n\x04\x64\x61te\x18\x0c \x01(\t\x12\x0c\n\x04open\x18\x02 \x01(\x01\x12\r\n\x05\x63lose\x18\x03 \x01(\x01\x12\x0c\n\x04high\x18\x04 \x01(\x01\x12\x0b\n\x03low\x18\x05 \x01(\x01\x12\x0e\n\x06volumn\x18\x06 \x01(\x01\x12*\n\"option_put_price_for_1_cut_3_month\x18\x07 \x01(\x01\x12\x10\n\x08\x64ividend\x18\x08 \x01(\x08\x12\r\n\x05yield\x18\t \x01(\x08\x12 \n\x18last_revenue_report_date\x18\n \x01(\t\x12 \n\x18next_revenue_report_date\x18\x0b \x01(\t')
)




_STOCKINFO_STOCKSUMMARYINFO = _descriptor.Descriptor(
  name='StockSummaryInfo',
  full_name='StockInfo.StockSummaryInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='market_place', full_name='StockInfo.StockSummaryInfo.market_place', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("us").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ipo_date', full_name='StockInfo.StockSummaryInfo.ipo_date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='has_option_trade', full_name='StockInfo.StockSummaryInfo.has_option_trade', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='market_value_b', full_name='StockInfo.StockSummaryInfo.market_value_b', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_etf', full_name='StockInfo.StockSummaryInfo.is_etf', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_china', full_name='StockInfo.StockSummaryInfo.is_china', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=309,
)

_STOCKINFO_STOCKDAILYINFO = _descriptor.Descriptor(
  name='StockDailyInfo',
  full_name='StockInfo.StockDailyInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='StockInfo.StockDailyInfo.date', index=0,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='open', full_name='StockInfo.StockDailyInfo.open', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='close', full_name='StockInfo.StockDailyInfo.close', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='high', full_name='StockInfo.StockDailyInfo.high', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='low', full_name='StockInfo.StockDailyInfo.low', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='volumn', full_name='StockInfo.StockDailyInfo.volumn', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='option_put_price_for_1_cut_3_month', full_name='StockInfo.StockDailyInfo.option_put_price_for_1_cut_3_month', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dividend', full_name='StockInfo.StockDailyInfo.dividend', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yield', full_name='StockInfo.StockDailyInfo.yield', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_revenue_report_date', full_name='StockInfo.StockDailyInfo.last_revenue_report_date', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='next_revenue_report_date', full_name='StockInfo.StockDailyInfo.next_revenue_report_date', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=559,
)

_STOCKINFO = _descriptor.Descriptor(
  name='StockInfo',
  full_name='StockInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock_id', full_name='StockInfo.stock_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='summary_info', full_name='StockInfo.summary_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='daily_info', full_name='StockInfo.daily_info', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_STOCKINFO_STOCKSUMMARYINFO, _STOCKINFO_STOCKDAILYINFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=559,
)

_STOCKINFO_STOCKSUMMARYINFO.containing_type = _STOCKINFO
_STOCKINFO_STOCKDAILYINFO.containing_type = _STOCKINFO
_STOCKINFO.fields_by_name['summary_info'].message_type = _STOCKINFO_STOCKSUMMARYINFO
_STOCKINFO.fields_by_name['daily_info'].message_type = _STOCKINFO_STOCKDAILYINFO
DESCRIPTOR.message_types_by_name['StockInfo'] = _STOCKINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StockInfo = _reflection.GeneratedProtocolMessageType('StockInfo', (_message.Message,), dict(

  StockSummaryInfo = _reflection.GeneratedProtocolMessageType('StockSummaryInfo', (_message.Message,), dict(
    DESCRIPTOR = _STOCKINFO_STOCKSUMMARYINFO,
    __module__ = 'proto.stock_info_pb2'
    # @@protoc_insertion_point(class_scope:StockInfo.StockSummaryInfo)
    ))
  ,

  StockDailyInfo = _reflection.GeneratedProtocolMessageType('StockDailyInfo', (_message.Message,), dict(
    DESCRIPTOR = _STOCKINFO_STOCKDAILYINFO,
    __module__ = 'proto.stock_info_pb2'
    # @@protoc_insertion_point(class_scope:StockInfo.StockDailyInfo)
    ))
  ,
  DESCRIPTOR = _STOCKINFO,
  __module__ = 'proto.stock_info_pb2'
  # @@protoc_insertion_point(class_scope:StockInfo)
  ))
_sym_db.RegisterMessage(StockInfo)
_sym_db.RegisterMessage(StockInfo.StockSummaryInfo)
_sym_db.RegisterMessage(StockInfo.StockDailyInfo)


# @@protoc_insertion_point(module_scope)
